version: '3.4'

services:
#mssql docker
  elibrary-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - elibrarynet

  elibrary.api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eLibrary=Server=elibrary-sql,1433;Database=IB160088Docker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:5000
    networks:
      - elibrarynet    
    links:
      - elibrary-sql
    depends_on:
      - elibrary-sql
      
networks:
  elibrarynet:
    driver: bridge  