// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eLibrary.Database;

namespace eLibrary.Migrations
{
    [DbContext(typeof(eLibraryContext))]
    [Migration("20220215142539_RemoveNacinPlacanja")]
    partial class RemoveNacinPlacanja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eLibrary.Database.Models.Drzava", b =>
                {
                    b.Property<int>("Drzava_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivDrzave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Drzava_ID");

                    b.ToTable("Drzava");

                    b.HasData(
                        new
                        {
                            Drzava_ID = 1,
                            NazivDrzave = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Drzava_ID = 2,
                            NazivDrzave = "Hrvatska"
                        },
                        new
                        {
                            Drzava_ID = 3,
                            NazivDrzave = "Turska"
                        },
                        new
                        {
                            Drzava_ID = 4,
                            NazivDrzave = "Spanija"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Grad", b =>
                {
                    b.Property<int>("Grad_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Drzava_ID")
                        .HasColumnType("int");

                    b.Property<string>("NazivGrada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grad_ID");

                    b.HasIndex("Drzava_ID");

                    b.ToTable("Grad");

                    b.HasData(
                        new
                        {
                            Grad_ID = 1,
                            Drzava_ID = 1,
                            NazivGrada = "Sarajevo"
                        },
                        new
                        {
                            Grad_ID = 2,
                            Drzava_ID = 2,
                            NazivGrada = "Zagreb"
                        },
                        new
                        {
                            Grad_ID = 3,
                            Drzava_ID = 3,
                            NazivGrada = "Ankara"
                        },
                        new
                        {
                            Grad_ID = 4,
                            Drzava_ID = 4,
                            NazivGrada = "Barselona"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Knjiga", b =>
                {
                    b.Property<int>("Knjiga_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivKnjige")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PDFDodan")
                        .HasColumnType("bit");

                    b.Property<int>("Pisac_ID")
                        .HasColumnType("int");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Zanr_ID")
                        .HasColumnType("int");

                    b.HasKey("Knjiga_ID");

                    b.HasIndex("Pisac_ID");

                    b.HasIndex("Zanr_ID");

                    b.ToTable("Knjiga");

                    b.HasData(
                        new
                        {
                            Knjiga_ID = 1,
                            Cijena = 49.990000000000002,
                            DatumIzdavanja = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(2667),
                            NazivKnjige = "Na Drini cuprija",
                            Ocjena = 5.0,
                            Opis = "Priča počinje s uvjetima života u Višegradu prije nego što je most sagrađen, a onda se nastavlja na njegovu izgradnju u 16. stoljeću. Nakon toga govori o životu u kasabi koji je usko vezan uz most. Preko njega prolaze putnici, trgovci i mještani. Svaki veliki događaj, bio sretan ili ne, obilježava se prelaskom preko mosta. ",
                            PDF = "nadrinicuprija.pdf",
                            PDFDodan = true,
                            Pisac_ID = 1,
                            Zanr_ID = 1
                        },
                        new
                        {
                            Knjiga_ID = 2,
                            Cijena = 39.990000000000002,
                            DatumIzdavanja = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(3203),
                            NazivKnjige = "Dnevnik Ane Frank",
                            Ocjena = 4.7000000000000002,
                            Opis = "Annin dnevnik pisan je u vremenskom razdoblju od 1942 do 1944. godine, najteža vremena Drugog svjetskog rata u Europi. Kamo god krenuli, Hitlerova je vojska širila otrov antisemitizma i rasne mržnje. ",
                            PDF = "dnevnikanefrank.pdf",
                            PDFDodan = true,
                            Pisac_ID = 2,
                            Zanr_ID = 2
                        },
                        new
                        {
                            Knjiga_ID = 3,
                            Cijena = 10.0,
                            DatumIzdavanja = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(3212),
                            NazivKnjige = "Pjesme",
                            Ocjena = 4.4000000000000004,
                            Opis = "Ovo su pjesme Sidran Abdulaha ",
                            PDF = "1001noc.pdf",
                            PDFDodan = true,
                            Pisac_ID = 3,
                            Zanr_ID = 3
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Korisnik", b =>
                {
                    b.Property<int>("Korisnik_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grad_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Spol_ID")
                        .HasColumnType("int");

                    b.Property<int>("Uloga_ID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Korisnik_ID");

                    b.HasIndex("Grad_ID");

                    b.HasIndex("Spol_ID");

                    b.HasIndex("Uloga_ID");

                    b.ToTable("Korisnik");

                    b.HasData(
                        new
                        {
                            Korisnik_ID = 1,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 275, DateTimeKind.Local).AddTicks(6815),
                            Email = "admin@gmail.com",
                            Grad_ID = 1,
                            Ime = "Admin",
                            PasswordHash = "YAWTUq0ie8c0tBtxDe8Cv5BcEkU=",
                            PasswordSalt = "2347UVaXDf0JXS/13WCCdg==",
                            Prezime = "Admin",
                            Spol_ID = 1,
                            Uloga_ID = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Korisnik_ID = 2,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 275, DateTimeKind.Local).AddTicks(8373),
                            Email = "korisnik@gmail.com",
                            Grad_ID = 3,
                            Ime = "Korisnik",
                            PasswordHash = "S27pePLiy7wnHja89giP/L4RQ6s=",
                            PasswordSalt = "S5felu6ihLLEtjNKQZMaSA==",
                            Prezime = "Korisnik",
                            Spol_ID = 1,
                            Uloga_ID = 2,
                            Username = "korisnik"
                        },
                        new
                        {
                            Korisnik_ID = 3,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 275, DateTimeKind.Local).AddTicks(8383),
                            Email = "almir.jusic@edu.fit.ba",
                            Grad_ID = 3,
                            Ime = "Almir",
                            PasswordHash = "Y/rtFbnRSgQ53PX3+w9lEoqiJ2s=",
                            PasswordSalt = "WqHzH1hIBtmsewpNDEpeGg==",
                            Prezime = "Jusic",
                            Spol_ID = 1,
                            Uloga_ID = 1,
                            Username = "almir"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.KorisnikKnjigaKomentar", b =>
                {
                    b.Property<int>("KorisnikKnjigaKomentar_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumKomentara")
                        .HasColumnType("datetime2");

                    b.Property<int>("Knjiga_ID")
                        .HasColumnType("int");

                    b.Property<int>("Korisnik_ID")
                        .HasColumnType("int");

                    b.Property<string>("SadrzajKomentara")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikKnjigaKomentar_ID");

                    b.HasIndex("Knjiga_ID");

                    b.HasIndex("Korisnik_ID");

                    b.ToTable("KorisnikKnjigaKomentar");

                    b.HasData(
                        new
                        {
                            KorisnikKnjigaKomentar_ID = 1,
                            DatumKomentara = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(8449),
                            Knjiga_ID = 3,
                            Korisnik_ID = 2,
                            SadrzajKomentara = "Knjiga je sasvim okeej!"
                        },
                        new
                        {
                            KorisnikKnjigaKomentar_ID = 2,
                            DatumKomentara = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(8811),
                            Knjiga_ID = 2,
                            Korisnik_ID = 2,
                            SadrzajKomentara = "Knjiga je užasno dosadna!"
                        },
                        new
                        {
                            KorisnikKnjigaKomentar_ID = 3,
                            DatumKomentara = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(8819),
                            Knjiga_ID = 1,
                            Korisnik_ID = 2,
                            SadrzajKomentara = "Preporucujem knjiguu!"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.KorisnikKnjigaOcjena", b =>
                {
                    b.Property<int>("KorisnikKnjigaOcjena_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumOcjene")
                        .HasColumnType("datetime2");

                    b.Property<int>("Knjiga_ID")
                        .HasColumnType("int");

                    b.Property<int>("Korisnik_ID")
                        .HasColumnType("int");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.HasKey("KorisnikKnjigaOcjena_ID");

                    b.HasIndex("Knjiga_ID");

                    b.HasIndex("Korisnik_ID");

                    b.ToTable("KorisnikKnjigaOcjena");

                    b.HasData(
                        new
                        {
                            KorisnikKnjigaOcjena_ID = 1,
                            DatumOcjene = new DateTime(2022, 2, 15, 15, 25, 39, 277, DateTimeKind.Local).AddTicks(1395),
                            Knjiga_ID = 3,
                            Korisnik_ID = 2,
                            Ocjena = 4.5
                        },
                        new
                        {
                            KorisnikKnjigaOcjena_ID = 2,
                            DatumOcjene = new DateTime(2022, 2, 15, 15, 25, 39, 277, DateTimeKind.Local).AddTicks(1633),
                            Knjiga_ID = 2,
                            Korisnik_ID = 2,
                            Ocjena = 4.9000000000000004
                        },
                        new
                        {
                            KorisnikKnjigaOcjena_ID = 3,
                            DatumOcjene = new DateTime(2022, 2, 15, 15, 25, 39, 277, DateTimeKind.Local).AddTicks(1640),
                            Knjiga_ID = 1,
                            Korisnik_ID = 2,
                            Ocjena = 4.0999999999999996
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.KupovinaKnjige", b =>
                {
                    b.Property<int>("KupovinaKnjige_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumKupovine")
                        .HasColumnType("datetime2");

                    b.Property<int>("Knjiga_ID")
                        .HasColumnType("int");

                    b.Property<int>("Korisnik_ID")
                        .HasColumnType("int");

                    b.Property<bool?>("Odobreno")
                        .HasColumnType("bit");

                    b.HasKey("KupovinaKnjige_ID");

                    b.HasIndex("Knjiga_ID");

                    b.HasIndex("Korisnik_ID");

                    b.ToTable("KupovinaKnjige");

                    b.HasData(
                        new
                        {
                            KupovinaKnjige_ID = 1,
                            DatumKupovine = new DateTime(2022, 2, 15, 15, 25, 39, 277, DateTimeKind.Local).AddTicks(4004),
                            Knjiga_ID = 1,
                            Korisnik_ID = 2,
                            Odobreno = true
                        },
                        new
                        {
                            KupovinaKnjige_ID = 2,
                            DatumKupovine = new DateTime(2022, 2, 15, 15, 25, 39, 277, DateTimeKind.Local).AddTicks(4378),
                            Knjiga_ID = 3,
                            Korisnik_ID = 2,
                            Odobreno = false
                        },
                        new
                        {
                            KupovinaKnjige_ID = 3,
                            DatumKupovine = new DateTime(2022, 2, 15, 15, 25, 39, 277, DateTimeKind.Local).AddTicks(4386),
                            Knjiga_ID = 2,
                            Korisnik_ID = 2,
                            Odobreno = true
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Pisac", b =>
                {
                    b.Property<int>("Pisac_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grad_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pisac_ID");

                    b.HasIndex("Grad_ID");

                    b.ToTable("Pisac");

                    b.HasData(
                        new
                        {
                            Pisac_ID = 1,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 273, DateTimeKind.Local).AddTicks(4428),
                            Grad_ID = 1,
                            Ime = "Abdulah",
                            Prezime = "Sidran"
                        },
                        new
                        {
                            Pisac_ID = 2,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 274, DateTimeKind.Local).AddTicks(9807),
                            Grad_ID = 4,
                            Ime = "Ivo",
                            Prezime = "Andric"
                        },
                        new
                        {
                            Pisac_ID = 3,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 274, DateTimeKind.Local).AddTicks(9829),
                            Grad_ID = 3,
                            Ime = "Mak",
                            Prezime = "Dizdar"
                        },
                        new
                        {
                            Pisac_ID = 4,
                            DatumRodjenja = new DateTime(2022, 2, 15, 15, 25, 39, 274, DateTimeKind.Local).AddTicks(9832),
                            Grad_ID = 2,
                            Ime = "Ana",
                            Prezime = "Frank"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.PrijedlogKnjige", b =>
                {
                    b.Property<int>("PrijedlogKnjige_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumPrijedloga")
                        .HasColumnType("datetime2");

                    b.Property<int>("Korisnik_ID")
                        .HasColumnType("int");

                    b.Property<string>("NazivPrijedlogaKnjige")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Odgovoren")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pregledan")
                        .HasColumnType("bit");

                    b.HasKey("PrijedlogKnjige_ID");

                    b.HasIndex("Korisnik_ID");

                    b.ToTable("PrijedlogKnjige");

                    b.HasData(
                        new
                        {
                            PrijedlogKnjige_ID = 1,
                            DatumPrijedloga = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(5281),
                            Korisnik_ID = 2,
                            NazivPrijedlogaKnjige = "Zeleno busenje",
                            Odgovoren = true,
                            Opis = "Ovaj zahtjev je odobren!",
                            Pregledan = true
                        },
                        new
                        {
                            PrijedlogKnjige_ID = 2,
                            DatumPrijedloga = new DateTime(2022, 2, 15, 15, 25, 39, 276, DateTimeKind.Local).AddTicks(5967),
                            Korisnik_ID = 2,
                            NazivPrijedlogaKnjige = "Orlovi rano lete",
                            Odgovoren = false,
                            Opis = "Cekanje na zahtjev!",
                            Pregledan = false
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Spol", b =>
                {
                    b.Property<int>("Spol_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OznakaSpola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Spol_ID");

                    b.ToTable("Spol");

                    b.HasData(
                        new
                        {
                            Spol_ID = 1,
                            OznakaSpola = "M"
                        },
                        new
                        {
                            Spol_ID = 2,
                            OznakaSpola = "Ž"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Uloga", b =>
                {
                    b.Property<int>("Uloga_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivUloge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uloga_ID");

                    b.ToTable("Uloga");

                    b.HasData(
                        new
                        {
                            Uloga_ID = 1,
                            NazivUloge = "Administrator",
                            Opis = "Ovaj uloga je administrator!"
                        },
                        new
                        {
                            Uloga_ID = 2,
                            NazivUloge = "Korisnik",
                            Opis = "Ovaj uloga je obicni korisnik!"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Zanr", b =>
                {
                    b.Property<int>("Zanr_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivZanra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Zanr_ID");

                    b.ToTable("Zanr");

                    b.HasData(
                        new
                        {
                            Zanr_ID = 1,
                            NazivZanra = "Horor"
                        },
                        new
                        {
                            Zanr_ID = 2,
                            NazivZanra = "Romantika"
                        },
                        new
                        {
                            Zanr_ID = 3,
                            NazivZanra = "Novela"
                        },
                        new
                        {
                            Zanr_ID = 4,
                            NazivZanra = "Naucna Fantastika"
                        });
                });

            modelBuilder.Entity("eLibrary.Database.Models.Grad", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("Drzava_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("eLibrary.Database.Models.Knjiga", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Pisac", "Pisac")
                        .WithMany()
                        .HasForeignKey("Pisac_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLibrary.Database.Models.Zanr", "Zanr")
                        .WithMany()
                        .HasForeignKey("Zanr_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pisac");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("eLibrary.Database.Models.Korisnik", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("Grad_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLibrary.Database.Models.Spol", "Spol")
                        .WithMany()
                        .HasForeignKey("Spol_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLibrary.Database.Models.Uloga", "Uloga")
                        .WithMany()
                        .HasForeignKey("Uloga_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("Spol");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eLibrary.Database.Models.KorisnikKnjigaKomentar", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Knjiga", "Knjiga")
                        .WithMany()
                        .HasForeignKey("Knjiga_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLibrary.Database.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("Korisnik_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knjiga");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eLibrary.Database.Models.KorisnikKnjigaOcjena", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Knjiga", "Knjiga")
                        .WithMany()
                        .HasForeignKey("Knjiga_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLibrary.Database.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("Korisnik_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Knjiga");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eLibrary.Database.Models.KupovinaKnjige", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Knjiga", "Knjiga")
                        .WithMany()
                        .HasForeignKey("Knjiga_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eLibrary.Database.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("Korisnik_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Knjiga");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eLibrary.Database.Models.Pisac", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("Grad_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("eLibrary.Database.Models.PrijedlogKnjige", b =>
                {
                    b.HasOne("eLibrary.Database.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("Korisnik_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });
#pragma warning restore 612, 618
        }
    }
}
